# Generated by Django 6.0.3 on 2026-04-10 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_member_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Features',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField(auto_now_add=True, verbose_name='Date of creation')),
                ('modify', models.DateField(auto_now=True, verbose_name='Updated')),
                ('active', models.BooleanField(default=True, verbose_name='Active?')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('description', models.TextField(max_length=300, verbose_name='Description')),
                ('icon', models.CharField(choices=[('lni-rocket', 'Rocket'), ('lni-laptop-phone', 'Responsive'), ('lni-cog', 'Gear'), ('lni-leaf', 'Leaf'), ('lni-layers', 'Layers')], max_length=16, verbose_name='Icon')),
            ],
            options={
                'verbose_name': 'Feature',
                'verbose_name_plural': 'Features',
            },
        ),
    ]
